api/urls.py
from django.urls import path

from api.views import ProductListAPIView

app_name = 'api'
urlpatterns = [
    path('products/', ProductListAPIView.as_view())

]

felix/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('products/', include('products.urls', namespace='products')),
    path('profile/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls', namespace='api')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderHistoryListView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('history/', OrderHistoryListView.as_view(), name='history')
]

pages/urls.py
from django.urls import path, include

from pages.views import HomeView, WishlistListView, add_to_wishlist, ContactCreateView

app_name = 'pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('wishlist/', WishlistListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),

]

products/urls.py
from django.urls import path

from products.views import ProductListView, ProductDetailView, add_to_cart, CartListView, CommentCreateView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
]

users/urls.py
from django.urls import path

from users.views import ProfileUpdateView

app_name = 'profile'

urlpatterns = [
    path('', ProfileUpdateView.as_view(), name='home'),
]

templates/layouts/footer.html
{% load static %}

<footer class="footer section section-sm" style="background-color: #575965;color: white">
    <!-- Container Start -->
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-7 offset-md-1 offset-lg-0">
                <!-- About -->
                <div class="block about">
                    <!-- footer logo -->
                    <img src="images/logo-footer.png" alt="">
                    <!-- description -->
                    <p class="alt-color">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
            </div>
            <!-- Link list -->
            <div class="col-lg-2 offset-lg-1 col-md-3">
                <div class="block">
                    <h4>Site Pages</h4>
                    <ul>
                        <li><a href="#">Boston</a></li>
                        <li><a href="#">How It works</a></li>
                        <li><a href="#">Deals & Coupons</a></li>
                        <li><a href="#">Articls & Tips</a></li>
                        <li><a href="terms-condition.html">Terms & Conditions</a></li>
                    </ul>
                </div>
            </div>

            {##}
            {##}
            {##}
            {#          </ul>#}
            {#        </div>#}
            {#      </div>#}

            <div class="col-md-6">
                <div class="sidebar">
                    <div class="widget map">
                        <div class="map">
                            <div id="map_canvas" data-latitude="51.507351"
                                 data-longitude="-0.127758"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Container End -->
</footer>
<!-- Footer Bottom -->
<footer class="footer-bottom">
    <!-- Container Start -->
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-12">
                <!-- Copyright -->
                <div class="copyright text-center">
                    <p>Created by Kenjaev.S ©
                        <script>
                            var CurrentYear = new Date().getFullYear()
                            document.write(CurrentYear)
                        </script>
                    </p>
                </div>
            </div>
            <div class="col-sm-6 col-12">
                <!-- Social Icons -->
                <ul class="social-media-icons text-right">
                    <li><a class="fa fa-facebook" href="https://www.facebook.com/themefisher" target="_blank"></a></li>
                    <li><a class="fa fa-twitter" href="https://www.twitter.com/themefisher" target="_blank"></a></li>
                    <li><a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher" target="_blank"></a>
                    </li>
                    <li><a class="fa fa-vimeo" href=""></a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Container End -->
    <!-- To Top -->
    <div class="top-to">
        <a id="top" class="" href="#"><i class="fa fa-angle-up"></i></a>
    </div>
</footer>

templates/layouts/header.html
{% load i18n %}
{% load static %}
{% load mytags %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light navigation">
                    <a class="navbar-brand" href="index.html">
                        <img src="{% static 'images/logo.png' %}" alt="">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto main-nav">
                            <li class="nav-item active">
                                <a style="font-size: 25px;font-family:Muli, sans-serif; " class="nav-link"
                                   href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                            </li>
                            <li class="nav-item">
                                <a style="font-size: 25px;font-family:Muli, sans-serif;" class="nav-link"
                                   href="{% url 'products:list' %}">{% trans 'Products' %}</a>
                            </li>
                            <li class="nav-item">
                                <a style="font-size: 25px;font-family:Muli, sans-serif;" class="nav-link"
                                   href="{% url 'pages:contact' %}">{% trans 'Contact' %}</a>
                            </li>


                        </ul>
                        <ul class="navbar-nav ml-auto mt-10">
                            {% if request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="pr-3" href="{% url 'profile:home' %}"><i
                                            style="font-size: 25px;margin-top:6px;color: #212529" class="fa fa-user"
                                            aria-hidden="true"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a class="pr-3" href="{% url 'orders:history' %}"><i
                                            style="font-size: 25px;margin-top:6px;color: #212529" class="fa fa-history"
                                            aria-hidden="true"></i></a>
                                </li>

                                <li class="nav-item">
                                    <a class="pr-3" href="{% url 'pages:wishlist' %}"><i
                                            style="font-size: 25px;margin-top:6px;color: #212529" class="fa fa-heart"
                                            aria-hidden="true"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a class="pr-3" href="{% url 'products:cart' %}"><i
                                            style="font-size: 25px;margin-top:6px;color: #212529"
                                            class="fa fa-shopping-cart" aria-hidden="true"></i>
                                        <span>{% cart_count request %}</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link login-button"
                                       href="{% url 'auth_logout' %}">{% trans 'Log out' %}</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link login-button"
                                       href="{% url 'auth_login' %}">{% trans "Login" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="pr-3" href="{% url 'products:cart' %}"><i
                                            style="font-size: 30px;color: #212529" class="fa fa-shopping-cart"
                                            aria-hidden="true"></i>
                                        <span>{% cart_count request %}</span></a>
                                </li>
                            {% endif %}
               <div class="header__top__hover">
                            {% get_current_language as lang %}
                            {% get_available_languages as langs %}
                            <span>{{ lang }} <i class="arrow_carrot-down"></i></span>
                            <ul>
                                {% for l in langs %}
                                    {% if l.0 != lang %}
                                        <li>
                                            <a href="{% get_lang_url request l.0 %}"
                                               style="color: #111; text-decoration: none">{{ l.0|upper }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>


                            {#							<li class="nav-item">#}
                            {#								<a class="nav-link text-white add-button" href="ad-listing.html"><i class="fa fa-plus-circle"></i> Add Listing</a>#}
                            {#							</li>#}
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</section>