api/urls.py
from django.urls import path

from api.views import ProductListAPIView

app_name = 'api'
urlpatterns = [
    path('products/', ProductListAPIView.as_view())

]

felix/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('products/', include('products.urls', namespace='products')),
    path('profile/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls', namespace='api')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderHistoryListView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('history/', OrderHistoryListView.as_view(), name='history')
]

pages/urls.py
from django.urls import path, include

from pages.views import HomeView, WishlistListView, add_to_wishlist, ContactCreateView

app_name = 'pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('wishlist/', WishlistListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),

]

products/urls.py
from django.urls import path

from products.views import ProductListView, ProductDetailView, add_to_cart, CartListView, CommentCreateView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
]

users/urls.py
from django.urls import path

from users.views import ProfileUpdateView

app_name = 'profile'

urlpatterns = [
    path('', ProfileUpdateView.as_view(), name='home'),
]

products/models.py
from datetime import datetime
from django.utils.translation import ugettext_lazy as _
import pytz
from django.contrib.auth import get_user_model
from django.db import models
UserModel = get_user_model()

class CategoryModel(models.Model):
    title = models.CharField(max_length=550,verbose_name=_('title'))
    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class GenderModel(models.Model):
    title = models.CharField(max_length=550,verbose_name=_('title'))
    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = _('gender')
        verbose_name_plural = _('genders')


class ColorsModel(models.Model):
    title = models.CharField(max_length=15, null=True, blank=True,verbose_name=_('title'))
    code = models.CharField(max_length=12,verbose_name=_('code'))
    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = _('color')
        verbose_name_plural = _('colors')


class BrandModel(models.Model):
    title = models.CharField(max_length=550,verbose_name=_('title'))
    image = models.ImageField(upload_to='brands',verbose_name=_('image'))
    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name =_( 'brand')
        verbose_name_plural = _('brands')


class ProductTagModel(models.Model):
    title = models.CharField(max_length=550,verbose_name=_('title'))
    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class SizeModel(models.Model):
    title = models.CharField(max_length=3,verbose_name=_('title'))
    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = _('size')
        verbose_name_plural = _('sizes')


class ProductsModel(models.Model):
    title = models.CharField(max_length=550,verbose_name=_('title'))
    category = models.ForeignKey(CategoryModel, on_delete=models.PROTECT, related_name='products',verbose_name=_('category'))
    gender = models.ForeignKey(GenderModel, on_delete=models.PROTECT, related_name='product',verbose_name=_('gender'))
    price = models.FloatField(verbose_name=_('price'))
    brand = models.ForeignKey(BrandModel, on_delete=models.PROTECT, related_name='products',verbose_name=_('brand'))
    discount = models.PositiveIntegerField(default=0,verbose_name=_('discount'))
    description = models.TextField(verbose_name=_('description'))
    tags = models.ManyToManyField(ProductTagModel, related_name='products',verbose_name=_('tags'))
    model = models.CharField(max_length=30,verbose_name=_('model'))
    wishlist = models.ManyToManyField(UserModel, related_name='wishlist',verbose_name=_('wishlist'))
    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))
    real_price = models.FloatField(default=0,verbose_name=_('real_price'))
    sizes = models.ManyToManyField(SizeModel, related_name='products',verbose_name=_('sizes'))
    colors = models.ManyToManyField(ColorsModel, related_name='products',verbose_name=_('colors'))


    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')


    @staticmethod
    def get_from_cart(request):
        cart = request.session.get('cart', [])

        return ProductsModel.objects.filter(pk__in=cart)

    def get_image(self):
        images = self.images.all()
        if images:
            return self.images.first().image.url
        return '/static/img/noimage.png'

    def get_comments(self):
        return self.comments.order_by('-created_at')

    def is_discount(self):
        return self.discount != 0

    def get_price(self):
        if self.is_discount():
            return self.price - self.price * self.discount / 100
        return round(self.price, 2)

    def is_new(self):
        delta = datetime.now(pytz.timezone('Asia/Tashkent')) - self.created_at
        return delta.days <= 3


class ProductImageModel(models.Model):
    image = models.ImageField(upload_to='products',verbose_name=_('image'))
    product = models.ForeignKey(ProductsModel, on_delete=models.CASCADE, related_name='images',verbose_name=_('product'))

    def __str__(self):
        return f'{self.product.title}'

    class Meta:
        verbose_name = _('product image')
        verbose_name_plural = _('product images')


class CommentModel(models.Model):
    name = models.CharField(max_length=30,verbose_name=_('created_at'))
    email = models.EmailField(verbose_name=_('email'))
    comment = models.TextField(verbose_name=_('comment'))

    product = models.ForeignKey(ProductsModel, related_name='comments', on_delete=models.CASCADE,verbose_name=_('product'))

    created_at = models.DateTimeField(auto_now_add=True,verbose_name=_('created_at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

products/forms.py
from django import forms

from products.models import CommentModel, ColorsModel


class CommentModelForm(forms.ModelForm):
    class Meta:
        exclude = ['created_at', 'product']
        model = CommentModel

products/views.py
from math import ceil

from django.db.models import Q, Min, Max
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView

from products.forms import CommentModelForm
from products.models import ProductsModel, CategoryModel, ProductTagModel, BrandModel, SizeModel, GenderModel, \
    ColorsModel



class ProductListView(ListView):
    template_name = 'products.html'
    paginate_by = 9

    def get_queryset(self):
        qs = ProductsModel.objects.order_by('-pk')
        q = self.request.GET.get('q')
        cat = self.request.GET.get('cat')
        brand = self.request.GET.get('brand')
        tag = self.request.GET.get('tag')
        size = self.request.GET.get('size')
        price = self.request.GET.get('price')

        if q:
            qs = qs.filter(Q(title__icontains=q))
        if cat:
            qs = qs.filter(category__id=cat)
        if brand:
            qs = qs.filter(brand__id=brand)


        if price:
            price = price.split(';')
            price_from, price_to = price
            qs = qs.filter(real_price__gte=price_from, real_price__lte=price_to)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        context['tags'] = ProductTagModel.objects.all()
        context['brands'] = BrandModel.objects.all()
        context['size'] = SizeModel.objects.all()
        context['gender'] = GenderModel.objects.all()
        context['colors'] = ColorsModel.objects.all()


        max_price, min_price = ProductsModel.objects.aggregate(Max('real_price'), Min('real_price')).values()

        context['min_price'] = ceil(min_price)
        context['max_price'] = ceil(max_price)
        return context


class ProductDetailView(DetailView):
    template_name = 'product.html'
    model = ProductsModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related_products'] = self.object.brand.products.exclude(pk=self.object.pk)[:8]

        return context


def add_to_cart(request, pk):
    cart = request.session.get('cart')

    if not cart:
        cart = []

    if pk in cart:
        cart.remove(pk)
    else:
        cart.append(pk)

    request.session['cart'] = cart
    return redirect(request.GET.get('next', '/'))



class CartListView(ListView):
    template_name = 'shopping-cart.html'

    def get_queryset(self):
        cart = self.request.session.get('cart', [])
        return ProductsModel.objects.filter(pk__in=cart)




class CommentCreateView(CreateView):
    form_class = CommentModelForm

    def get_success_url(self):
        return reverse('products:detail', kwargs={'pk': self.kwargs.get('pk')})

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        form.instance.product = get_object_or_404(ProductsModel, pk=pk)
        return super().form_valid(form)

templates/contact-us.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section class="page-title" style="background-color: #212529">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2 text-center">
				<!-- Title text -->
				<h3>{% trans "Contact Us" %}</h3>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>
<!-- page title -->

<!-- contact us start-->
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="contact-us-content p-4">
                    <h5>{% trans 'Contact Us' %}</h5>
                    <h1 class="pt-3">Hello, what's on your mind?</h1>
                    <p class="pt-3 pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elit dolor, blandit vel euismod ac, lentesque et dolor. Ut id tempus ipsum.</p>
                </div>
            </div>
            <div class="col-md-6">
                    <form action="{% url 'pages:contact' %}" method="post" >
                        {% csrf_token %}
                        <fieldset class="p-4">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-6 py-2">
                                        <input name="name" type="text" placeholder="{% trans 'Name' %} *" class="form-control">
                                    </div>
                                    <div class="col-lg-6 pt-2">
                                        <input name="email" type="email" placeholder="Email *" class="form-control">
                                    </div>
                                     <div class="col-lg-6 pt-2">
                                        <input name="phone" type="text" placeholder="{% trans 'Phone' %} *" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <textarea name="text" id=""  placeholder="{% trans 'Message' %} *" class="border w-100 p-3 mt-3 mt-lg-4"></textarea>
                            <div class="btn-group">
                                <button type="submit" class="btn btn-dark mt-2 float-right" style="background-color: #212529;color: white">{% trans 'SUBMIT' %}</button>
                            </div>
                        </fieldset>
                    </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/shopping-cart.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load mytags %}
{% block extra_css %}
    <style>


        /*//////////////////////////////////////////////////////////////////
        [ FONT ]*/


        @font-face {
            font-family: OpenSans-Regular;
        }


        /*//////////////////////////////////////////////////////////////////
        [ RESTYLE TAG ]*/
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
        }

        /* ------------------------------------ */
        a {
            margin: 0px;
            transition: all 0.4s;
            -webkit-transition: all 0.4s;
            -o-transition: all 0.4s;
            -moz-transition: all 0.4s;
        }

        a:focus {
            outline: none !important;
        }

        a:hover {
            text-decoration: none;
        }

        /* ------------------------------------ */
        h1, h2, h3, h4, h5, h6 {
            margin: 0px;
        }

        p {
            margin: 0px;
        }

        ul, li {
            margin: 0px;
            list-style-type: none;
        }


        /* ------------------------------------ */
        input {
            display: block;
            outline: none;
            border: none !important;
        }

        textarea {
            display: block;
            outline: none;
        }

        textarea:focus, input:focus {
            border-color: transparent !important;
        }

        /* ------------------------------------ */
        button {
            outline: none !important;
            border: none;
            background: transparent;
        }

        button:hover {
            cursor: pointer;
        }

        iframe {
            border: none !important;
        }


        /*//////////////////////////////////////////////////////////////////
        [ Utiliti ]*/


        /*//////////////////////////////////////////////////////////////////
        [ Table ]*/

        .limiter {
            width: 100%;
            margin: 0 auto;
        }

        .container-table100 {
            width: 100%;
            min-height: 100vh;


            display: -webkit-box;
            display: -webkit-flex;
            display: -moz-box;
            display: -ms-flexbox;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-wrap: wrap;
            padding: 33px 30px;
        }

        .wrap-table100 {
            width: 1170px;
        }

        table {
            border-spacing: 1;
            border-collapse: collapse;
            background: white;
            border-radius: 10px;
            overflow: hidden;
            width: 100%;
            margin: 0 auto;
            position: relative;
        }

        table * {
            position: relative;
        }

        table td, table th {
            padding-left: 8px;
        }

        table thead tr {
            height: 60px;
            background: #36304a;
        }

        table tbody tr {
            height: 50px;
        }

        table tbody tr:last-child {
            border: 0;
        }

        table td, table th {
            text-align: left;
        }

        table td.l, table th.l {
            text-align: right;
        }

        table td.c, table th.c {
            text-align: center;
        }

        table td.r, table th.r {
            text-align: center;
        }


        .table100-head th {
            font-family: OpenSans-Regular;
            font-size: 18px;
            color: #fff;
            line-height: 1.2;
            font-weight: unset;
        }

        tbody tr:nth-child(even) {
            background-color: #f5f5f5;
        }

        tbody tr {
            font-family: OpenSans-Regular;
            font-size: 20px;
            color: #808080;
            line-height: 1.2;
            font-weight: unset;
        }

        tbody tr:hover {
            color: #555555;
            background-color: #f5f5f5;
            cursor: pointer;
        }

        .column1 {
            width: 260px;
            padding-left: 40px;
        }

        .column2 {
            width: 160px;
        }

        .column3 {
            width: 245px;
        }

        .column4 {
            width: 110px;
            text-align: right;
        }

        .column5 {
            width: 170px;
            text-align: right;
        }

        .column6 {
            width: 222px;
            text-align: right;
            padding-right: 62px;
        }


        @media screen and (max-width: 992px) {
            table {
                display: block;
            }

            table > *, table tr, table td, table th {
                display: block;
            }

            table thead {
                display: none;
            }

            table tbody tr {
                height: auto;
                padding: 37px 0;
            }

            table tbody tr td {
                padding-left: 40% !important;
                margin-bottom: 24px;
            }

            table tbody tr td:last-child {
                margin-bottom: 0;
            }

            table tbody tr td:before {
                font-family: OpenSans-Regular;
                font-size: 14px;
                color: #999999;
                line-height: 1.2;
                font-weight: unset;
                position: absolute;
                width: 40%;
                left: 30px;
                top: 0;
            }

            table tbody tr td:nth-child(1):before {
                content: "Date";
            }

            table tbody tr td:nth-child(2):before {
                content: "Order ID";
            }

            table tbody tr td:nth-child(3):before {
                content: "Name";
            }

            table tbody tr td:nth-child(4):before {
                content: "Price";
            }

            table tbody tr td:nth-child(5):before {
                content: "Quantity";
            }

            table tbody tr td:nth-child(6):before {
                content: "Total";
            }

            .column4,
            .column5,
            .column6 {
                text-align: left;
            }

            .column4,
            .column5,
            .column6,
            .column1,
            .column2,
            .column3 {
                width: 100%;
            }

            tbody tr {
                font-size: 14px;
            }
        }

        @media (max-width: 576px) {
            .container-table100 {
                padding-left: 15px;
                padding-right: 15px;
            }
        }
    </style>
{% endblock %}
{% block content %}

    <div class="limiter">
        <div class="container-table100">
            <div class="wrap-table100">
                <h1 class="text-center mb-3" style="font-family: OpenSans-Regular,serif">{% trans "Cart" %}</h1>
                <div class="table100">

                    <table style="border-radius: 4px">
                        <thead>
                        <tr class="table100-head">
                            <th class="column1">{% trans 'Date' %}</th>
                            <th class="column2">{% trans 'Brand' %}</th>
                            <th class="column3">{% trans 'Name' %}</th>

                            <th class="column4">{% trans 'Price' %}</th>
                            <th class="column5">{% trans 'Quantity' %}</th>
                            <th class="column6">{% trans 'Close' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td class="column1">{{ object.created_at|date:'d-m-y' }}</td>
                                <td class="column2">{{ object.brand.title }}</td>
                                <td class="column3">{{ object.title }}</td>
                                <td class="column4">${{ object.get_price }}</td>
                                <td class="column5">1</td>
                                <td class="cart__close">
                                    <a href="{% url 'products:add-to-cart' pk=object.pk %}?next={{ request.path }}{{ request.GET.urlencode }}">
                                        <i style="padding-left:120px;" class="fa fa-close"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>
                    <button class="btn btn-dark mt-3" style="background-color: #36304A"><a style="color: white" href="{% url 'orders:create' %}" class="primary-btn">{% trans 'Proceed to checkout' %}</a></button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block extra_js %}

    <script>
        (function ($) {
            "use strict";


        })(jQuery);
    </script>
{% endblock %}

templates/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% load mytags %}
{% block content %}
    <!--Grid row-->

    <!--Grid row-->
    <section class="dashboard section">
        <!-- Container Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
                <div class="col-md-10 offset-md-1 col-lg-4 offset-lg-0">
                    <div class="sidebar">
                        <!-- User Widget -->
                        <div class="widget user-dashboard-profile">
                            <!-- User Image -->
                            <div class="profile-thumb">
                                <img src="{% static 'images/user/user-thumb.jpg' %}" alt="" class="rounded-circle">
                            </div>
                            <!-- User Name -->
                            <h5 class="text-center">Samanta Doe</h5>
                            <p>Joined February 06, 2017</p>
                            <a href="{% url 'profile:home' %}" class="btn btn-main-sm">Edit Profile</a>
                        </div>
                        <div class="widget user-dashboard-menu">
                            <ul>
                                <li><a href="{% url 'products:cart' %}"><i class="fa fa-user"></i>Cart <span
                                        style="color: #52a7cc">({% cart_count request %})</span></a>
                                </li>
                                <li><a href="{% url 'pages:wishlist' %}"><i class="fa fa-bookmark-o"></i> Favourite
                                    Ads <span>5</span></a></li>
                                <li><a href="dashboard-archived-ads.html"><i
                                        class="fa fa-file-archive-o"></i>History<span>12</span></a></li>
                                <li><a href="{% url 'auth_logout' %}"><i class="fa fa-cog"></i> Logout</a></li>
                                <li><a href="" data-toggle="modal" data-target="#deleteaccount"><i
                                        class="fa fa-power-off"></i>Delete
                                    Account</a></li>
                            </ul>
                        </div>
                        <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalCenterTitle"
                             aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header border-bottom-0">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body text-center">
                                        <img src="{% static 'images/account/Account1.png' %}" class="img-fluid mb-2"
                                             alt="">
                                        <h6 class="py-2">Are you sure you want to delete your account?</h6>
                                        <p>Do you really want to delete these records? This process cannot be
                                            undone.</p>
                                        <textarea name="message" id="" cols="40" rows="4"
                                                  class="w-100 rounded"></textarea>
                                    </div>
                                    <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel
                                        </button>
                                        <button type="button" class="btn btn-danger">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-0">
                    <!-- Recently Favorited -->
                    <div class="widget dashboard-container my-adslist">
                        <h3 class="widget-header">My Favourite</h3>
                        <table class="table table-responsive product-dashboard-table">
                            <thead>
                            <tr>
                                <th>Image</th>
                                <th>Product Title</th>
                                <th class="text-center">Category</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for product in object_list %}
                                <tr>
                                    <td class="product-thumb">
                                        <img width="80px" height="auto" src="{{ product.get_image }}"
                                             alt="image description"></td>
                                    <td class="product-details">
                                        <h3 class="title">{{ product.title }}</h3>
                                        <span class="add-id"><strong>Ad ID:</strong> ng3D5hAMHPajQrM</span>
                                        <span class="location"><strong>Price</strong>${{ product.price }}</span>

                                        <span class="status active"><strong>Brand</strong>{{ product.brand.title }}</span>
                                        <span class="location"><strong>Location</strong>Dhaka,Bangladesh</span>
                                        <span><strong>Posted on: </strong><time>{{ product.created_at|date:'D-m-Y' }}</time> </span>

                                    </td>
                                    <td class="product-category"><span class="categories">{{ product.category }}</span>
                                    </td>
                                    <td class="action" data-title="Action">
                                        <div class="">
                                            <ul class="list-inline justify-content-center">
                                                <li class="list-inline-item">
                                                    <a data-toggle="tooltip" data-placement="top" title="view"
                                                       class="view" href="{% url 'products:detail' pk=product.pk %}">
                                                        <i class="fa fa-eye"></i>
                                                    </a>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a class="delete" data-toggle="tooltip" data-placement="top"
                                                       title="Delete"
                                                       href="{% url 'pages:add-wishlist' pk=product.pk %}?next={{ request.path }}{{ request.GET.urlencode }}">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            {% empty %}
                                <h4>List is empty</h4>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>

                    <!-- pagination -->
                    <div class="pagination justify-content-center">
                      <nav class="pagination-outer" aria-label="Page navigation">
                            <ul class="pagination">
                                 {% for page in page_obj.paginator.page_range %}
                                      <li class="page-item">
                                    <a style="padding: 10px" {% if page == page_obj.number %}class="active"{% endif %}
                                       href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                    <!-- pagination -->

                </div>
            </div>
            <!-- Row End -->
        </div>
        <!-- Container End -->
    </section>
{% endblock %}